### ISSUE TITLE
Specify python version required

### ISSUE THREAD

**Issue by jdrews** [gvalkov/tailon-legacy#12]
Looks like this might not work with 2.6.6 (which CentOS 6 ships with). Please specify minimum Python requirements. Thanks! 

```
[root@semantics logs]# tailon -f chandra.log
Traceback (most recent call last):
  File "/usr/bin/tailon", line 9, in <module>
    load_entry_point('tailon==0.4.1', 'console_scripts', 'tailon')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/tailon/main.py", line 203
    all_files = {i for values in config['files'].values() for i in values}
                     ^
SyntaxError: invalid syntax
[root@semantics logs]#
```

**Comment by jdrews** [comment]
Looks like you specify 2.7 and above required in #9. I'd like to leave this issue open until documentation can be updated to reflect this requirement.

**Comment by jdrews** [comment]
Documentation updated. Closing ticket.
