### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 38-39: invalid continuation byte

### ISSUE THREAD

**Issue by BoD** [gvalkov/tailon-legacy#24]
I am trying to use tailon and it works, until I have this problem:

```
[+6793350.006104][ERROR] Uncaught exception GET /ws/038/iu43uyrb/websocket (::1)
HTTPServerRequest(protocol='http', host='linode.jraf.org:8042', method='GET', uri='/ws/038/iu43uyrb/websocket', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://linode.jraf.org:8042', 'Upgrade': 'websocket', 'Accept-Language': 'en-US,en;q=0.8,fr;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Sec-Websocket-Version': '13', 'Host': 'linode.jraf.org:8042', 'Sec-Websocket-Key': 'KA3Wju4wP1bYxM2vIlGXOA==', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36', 'Connection': 'Upgrade', 'Cookie': '__utma=112708447.1942698661.1432803163.1432803163.1432803163.1; __utmc=112708447', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
Traceback (most recent call last):
  File "/Users/bod/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/Users/bod/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/Users/bod/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tailon/server.py", line 152, in stdout_callback
    msg = {fn: data.decode('utf8').splitlines(True)}
  File "/Users/bod/.pyenv/versions/2.7.10/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 38-39: invalid continuation byte
```

I attached a file that produces this issue.
[logcat.txt](https://github.com/gvalkov/tailon/files/176033/logcat.txt)

**Comment by gvalkov** [comment]
Hello @BoD and sorry for the atrocious response time. The issue was fixed in 91f0910719aead16fac01eecb7a246aef47a13dd. I'll close it once a new release with the fix is available. Thank you for reporting it.
