### ISSUE TITLE
Cannot start tailon v1.0 because of a missing 'tail-lines' key

### ISSUE THREAD

**Issue by asibin** [gvalkov/tailon-legacy#37]
Hello, I think i have found a bug in v1.0 of tailon.

When starting app with `tailon -c ~/test.yml`

This is the test.yml file:

```

---
bind: 0.0.0.0:8133      # address and port to bind on
allow-transfers: true   # allow log file downloads
relative-root: ''  # web app root path (default: '')
commands: [tail, grep]  # allowed commands
tail-lines: 100

files:
  - '/var/log/authd.log'
```

I get this output:

```
Traceback (most recent call last):
  File "/Users/sibin/.virtualenvs/tailon/bin/tailon", line 11, in <module>
    load_entry_point('tailon==1.0.0', 'console_scripts', 'tailon')()
  File "/Users/sibin/.virtualenvs/tailon/lib/python2.7/site-packages/tailon-1.0.0-py2.7.egg/tailon/main.py", line 268, in main
    'tail-lines-initial': config['tail-lines'],
KeyError: 'tail-lines'
```

Even though `tail-lines` was defined in config it wasn't read, what is worse it wouldn't start tailon at all because it was failing to get key.

Here is the pull request:
#36

Cheers,
Sibin

**Comment by gvalkov** [comment]
Hello @asibin . Thank you for the bug report and the fix!
