### ISSUE TITLE
Issues with newer version of Tornado when installing with pip.

### ISSUE THREAD

**Issue by br1guy** [gvalkov/tailon-legacy#49]
There seems to be an issue with a newer version of tornado that automatically gets installed when installing tailon with pip. The issue seems to be with tornado 5.0.0. Manually installed version 4.5.1 of tornado and had no issues. There is an issue with it complaining about the number of arguments. Not sure this is a tailon issue exactly, but it is what gets installed when installing tailon. 

Running this command: /bin/tailon -f /path/file.log --allow-transfers -b *:8805

Gets this error message:

Traceback (most recent call last):
  File "/bin/tailon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/tailon/main.py", line 284, in main
    cmd_control=cmd_control,
  File "/usr/lib/python2.7/site-packages/tailon/server.py", line 272, in __init__
    super(TailonApplication, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/site-packages/tailon/server.py", line 250, in __init__
    routes, self.ws_handler = self.setup_routes()
  File "/usr/lib/python2.7/site-packages/tailon/server.py", line 283, in setup_routes
    ws_handler = sockjs.tornado.SockJSRouter(WebsocketTailon, os.path.join('/', self.relative_root, 'ws'))
  File "/usr/lib/python2.7/site-packages/sockjs/tornado/router.py", line 111, in __init__
    self.io_loop)
TypeError: __init__() takes exactly 3 arguments (4 given)

**Comment by gvalkov** [comment]
Hi. Thanks for the catch. I just released 1.3.1 that pins tornado to <=5.0.0. [This issue](https://github.com/mrjoes/sockjs-tornado/pull/114) in `sock-js` needs to be fixed before tailon can support tornado 5.x.
