### ISSUE TITLE
`tailon -c` fails if `extra-files-dir` doesn't exit

### ISSUE THREAD

**Issue by petehalverson** [gvalkov/tailon-legacy#54]
```
$ tailon -v
tailon version 1.4.1

$ tailonc -c config.yml

Traceback (most recent call last):
  File "/usr/local/bin/tailon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tailon/main.py", line 282, in main
    config = setup(opts)
  File "/usr/local/lib/python2.7/dist-packages/tailon/main.py", line 213, in setup
    config = parseconfig(opts.config)
  File "/usr/local/lib/python2.7/dist-packages/tailon/main.py", line 81, in parseconfig
    for file in os.listdir(config['extra-files-dir']):
OSError: [Errno 2] No such file or directory: '/etc/tailon/files.d/'

$ mkdir -p /etc/tailon/files.d
$ tailonc -c config.yml

[+61.144829][ INFO] Listening on 0.0.0.0:8080
```

**Comment by petehalverson** [comment]
```yml
# config.yml
bind: 0.0.0.0:8080
allow-transfers: false
follow-names: false
commands: [tail, grep]
tail-lines: 10
wrap-lines: false
files:
  - /var/www/html/storage/logs/system.log
```
