### ISSUE TITLE
Syntax error in main.py

### ISSUE THREAD

**Issue by sesopenko** [gvalkov/tailon-legacy#9]
I'm using python version 2.6.6 on CentOS 6.5.  I've installed tailon with pip and get the following error when trying to run tailon:

```
Traceback (most recent call last):
  File "/usr/bin/tailon", line 7, in <module>
    from tailon.main import main
  File "/usr/lib/python2.6/site-packages/tailon/main.py", line 18, in <module>
    from . server import Application, Commands
  File "/usr/lib/python2.6/site-packages/tailon/server.py", line 99
    files = {name: Files.statfiles(lst) for name, lst in files.items()}

SyntaxError: invalid syntax
```

I've tried it with the latest development as well.

**Comment by gvalkov** [comment]
Tailon was written with Python `>= 2.7` in mind. While this error is trivial to fix, it's probably not the only incompatibility. With that said, I am reluctant to add support for 2.6. Sorry.

If your situation allows it, installing Python 2.7/3.3 on CentOS 6 is rather straightforward these days:
http://wiki.centos.org/AdditionalResources/Repositories/SCL

**Comment by jdrews** [comment]
Can confirm installing python2.7 from SCL works on CentOS 6.6

```
# yum install centos-release-SCL
# yum install python27
# scl enable python27 bash
# easy_install-2.7 pip
# pip2.7 install git+git://github.com/gvalkov/tailon.git
```

**Comment by gvalkov** [comment]
Yes, I should have mentioned that from the start. Cheers to SCL.

**Comment by shan0807** [comment]
I tried installing python2.7 from SCL but for 

# easy_install-2.7 pip

it says "sudo: easy_install-2.7: command not found"

**Comment by gvalkov** [comment]
I think `sudo` is resetting the environment (and `sudo -E` doesn't work for some reason). Try `sudo -i` followed by `scl enable python27 bash` and `easy_install` as root. Alternatively, since pip is already installed you can just install python-evdev as a user. The steps would be:

```
sudo yum install -y centos-release-SCL
sudo yum install -y python27 gcc kernel-headers
scl enable python27 bash
python -m pip install --user evdev
```

**Comment by shan0807** [comment]
It worked, thanks

Facing the following errors  
"tailon -f /var/log/nginx/*
/opt/rh/python27/root/usr/bin/python2: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory"

There are issues if we update the python from 2.6 to 2.7

**Comment by shan0807** [comment]
```
 tailon -f
Traceback (most recent call last):
  File "/usr/bin/tailon", line 7, in <module>
    from tailon.main import main
  File "/usr/lib/python2.6/site-packages/tailon/main.py", line 17, in <module>
    from . import commands
  File "/usr/lib/python2.6/site-packages/tailon/commands.py", line 15
    command_names = {'grep', 'awk', 'sed', 'tail'}

```
It still takes the value of python2.6 when python 2.7 is running on my machine. 
How to change the path for that

**Comment by shan0807** [comment]
I used the following code and tailon ran successfully. But, on machine reboot, it again takes python 2.6.6 as the default python version in centos6.x version.
Any work around for this
